<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>$(EPPlusCoreTargetFrameworks)</TargetFrameworks>
	    <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
		<Company>EPPlus Software AB</Company>
		<Product>EPPlus</Product>
		<Description>A spreadsheet library for .NET framework and .NET core</Description>
		<IsPackable>false</IsPackable>
		<NeutralLanguage />
		<LangVersion>latest</LangVersion>
		<SignAssembly>True</SignAssembly>
		<AssemblyOriginatorKeyFile>EPPlus.DrawingRenderer.snk</AssemblyOriginatorKeyFile>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="RenderItems\Shared\GroupItem.cs" />
	  <Compile Remove="RenderItems\Shared\InnerGroup.cs" />
	  <Compile Remove="RenderItems\Shared\ParagraphItem.cs" />
	  <Compile Remove="RenderItems\Shared\TextBodyItem.cs" />
	  <Compile Remove="RenderItems\Shared\TextRunCollection.cs" />
	  <Compile Remove="RenderItems\Shared\TextRunItem.cs" />
	  <Compile Remove="RenderItems\Shared\TransformGroup.cs" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EPPlus.Graphics\EPPlus.Graphics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="resource\presetShapeDefinitions.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="RenderItems\Shared\" />
  </ItemGroup>

</Project>
