<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0;netstandard2.1;netstandard2.0;net462</TargetFrameworks>
		<AssemblyVersion>9.0.0.0</AssemblyVersion>
	    <FileVersion>9.0.0.0</FileVersion>
	    <Version>9.0.0.0</Version>
	    <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
		<Company>EPPlus Software AB</Company>
		<Product>EPPlus</Product>
		<Description>A spreadsheet library for .NET framework and .NET core</Description>
		<NeutralLanguage />
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

  <ItemGroup>
    <Compile Remove="RenderItems\**" />
    <EmbeddedResource Remove="RenderItems\**" />
    <None Remove="RenderItems\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="RenderItems\GradientFill.cs" />
    <Compile Include="RenderItems\GradientFillColor.cs" />
    <Compile Include="RenderItems\Interfaces\IBorder.cs" />
    <Compile Include="RenderItems\Interfaces\IFill.cs" />
    <Compile Include="RenderItems\Interfaces\IRectItem.cs" />
    <Compile Include="RenderItems\Interfaces\IRender.cs" />
    <Compile Include="RenderItems\Interfaces\IStylingInfo.cs" />
    <Compile Include="RenderItems\Interfaces\IStylingInfoBase.cs" />
    <Compile Include="RenderItems\PathCommandType.cs" />
    <Compile Include="RenderItems\RenderDrawingBlipFill.cs" />
    <Compile Include="RenderItems\RenderItem.cs" />
    <Compile Include="RenderItems\RenderPatternFill.cs" />
    <Compile Include="RenderItems\RenderShadowEffect.cs" />
    <Compile Include="RenderItems\Shared\GroupItem.cs" />
    <Compile Include="RenderItems\Shared\InnerGroup.cs" />
    <Compile Include="RenderItems\Shared\ParagraphItem.cs" />
    <Compile Include="RenderItems\Shared\TextBodyItem.cs" />
    <Compile Include="RenderItems\Shared\TextRunCollection.cs" />
    <Compile Include="RenderItems\Shared\TextRunItem.cs" />
    <Compile Include="RenderItems\Shared\TransformGroup.cs" />
    <Compile Include="RenderItems\SvgBaseRenderer.cs" />
    <Compile Include="RenderItems\SvgDrawingCommands.cs" />
    <Compile Include="RenderItems\SvgExtensions.cs" />
    <Compile Include="RenderItems\SvgGroupItem.cs" />
    <Compile Include="RenderItems\SvgItem\ConnectionPointsMiddle.cs" />
    <Compile Include="RenderItems\SvgItem\eTextAnchor.cs" />
    <Compile Include="RenderItems\SvgItem\PointLines.cs" />
    <Compile Include="RenderItems\SvgItem\SvgChartSerieDataLabel.cs" />
    <Compile Include="RenderItems\SvgItem\SvgContainerItem.cs" />
    <Compile Include="RenderItems\SvgItem\SvgDataLabelPoint.cs" />
    <Compile Include="RenderItems\SvgItem\SvgGroupItemNew.cs" />
    <Compile Include="RenderItems\SvgItem\SvgInnerGroup.cs" />
    <Compile Include="RenderItems\SvgItem\SvgParagraphItem.cs" />
    <Compile Include="RenderItems\SvgItem\SvgTextBodyItem.cs" />
    <Compile Include="RenderItems\SvgItem\SvgTextBox.cs" />
    <Compile Include="RenderItems\SvgItem\SvgTextRunItem.cs" />
    <Compile Include="RenderItems\SvgItem\SvgTitleItem.cs" />
    <Compile Include="RenderItems\SvgItem\SvgTransformGroup.cs" />
    <Compile Include="RenderItems\SvgLineJoin.cs" />
    <Compile Include="RenderItems\SvgRenderEllipseItem.cs" />
    <Compile Include="RenderItems\SvgRenderItem.cs" />
    <Compile Include="RenderItems\SvgRenderLineItem.cs" />
    <Compile Include="RenderItems\SvgRenderPathItem.cs" />
    <Compile Include="RenderItems\SvgRenderRectItem.cs" />
    <Compile Include="RenderItems\SvgUseRefItem.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EPPlus.Graphics\EPPlus.Graphics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="resource\presetShapeDefinitions.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
