/*************************************************************************************************
  Required Notice: Copyright (C) EPPlus Software AB.
  This software is licensed under PolyForm Noncommercial License 1.0.0
  and may only be used for noncommercial purposes
  https://polyformproject.org/licenses/noncommercial/1.0.0/

  A commercial license to use this software can be purchased at https://epplussoftware.com
 *************************************************************************************************/
// <auto-generated>
//   This file was generated by EPPlus.Tools.Fonts. Do not edit by hand.
//   Generated on 2026-05-06 13:45:48Z
//   Entries: 45
// </auto-generated>

using System;
using System.Collections.Generic;

namespace EPPlus.Fonts.OpenType.FontResolver
{
    /// <summary>
    /// Built-in font fallback chains. Each entry maps a font family name to an ordered list
    /// of fallback names. Used by DefaultFontResolver when an exact match cannot be found
    /// and the user has not configured a custom fallback for the requested font.
    /// </summary>
    internal static class BuiltinFontFallbackChains
    {
        private static readonly Dictionary<string, string[]> _chains = BuildChains();

        /// <summary>
        /// Returns the ordered fallback chain for the given font name, or null if no chain is defined.
        /// Lookup is case-insensitive.
        /// </summary>
        internal static string[] GetFallbacks(string fontName)
        {
            if (string.IsNullOrEmpty(fontName))
                return null;

            string[] result;
            return _chains.TryGetValue(fontName, out result) ? result : null;
        }

        private static Dictionary<string, string[]> BuildChains()
        {
            var d = new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase);

            d[@"Aptos"] = new string[] { @"Carlito", @"Liberation Sans", @"Arial", @"Helvetica" };
            d[@"Aptos Display"] = new string[] { @"Carlito", @"Liberation Sans", @"Arial", @"Helvetica" };
            d[@"Aptos Light"] = new string[] { @"Carlito", @"Liberation Sans", @"Arial" };
            d[@"Aptos Mono"] = new string[] { @"Cascadia Mono", @"Cascadia Code", @"Consolas", @"Liberation Mono", @"Courier New" };
            d[@"Aptos Narrow"] = new string[] { @"Liberation Sans Narrow", @"Arial Narrow", @"Carlito", @"Liberation Sans", @"Arial" };
            d[@"Aptos SemiBold"] = new string[] { @"Carlito", @"Liberation Sans", @"Arial" };
            d[@"Arabic Transparent"] = new string[] { @"Arial" };
            d[@"Arabic Transparent Bold"] = new string[] { @"Arial Bold" };
            d[@"Arial"] = new string[] { @"Liberation Sans", @"Helvetica" };
            d[@"Arial Black"] = new string[] { @"Liberation Sans", @"Arial" };
            d[@"Arial Narrow"] = new string[] { @"Liberation Sans Narrow", @"Liberation Sans" };
            d[@"Book Antiqua"] = new string[] { @"Palatino Linotype", @"Palatino", @"Liberation Serif", @"Times New Roman" };
            d[@"Bookman Old Style"] = new string[] { @"Liberation Serif", @"Times New Roman", @"Times" };
            d[@"Calibri"] = new string[] { @"Carlito", @"Liberation Sans", @"Arial", @"Helvetica" };
            d[@"Calibri Light"] = new string[] { @"Carlito", @"Liberation Sans", @"Arial", @"Helvetica" };
            d[@"Cambria"] = new string[] { @"Caladea", @"Liberation Serif", @"Times New Roman", @"Times" };
            d[@"Cambria Math"] = new string[] { @"Latin Modern Math", @"STIX Two Math", @"Caladea", @"Liberation Serif" };
            d[@"Candara"] = new string[] { @"Carlito", @"Liberation Sans", @"Arial" };
            d[@"Century Gothic"] = new string[] { @"Liberation Sans", @"Arial", @"Helvetica" };
            d[@"Century Schoolbook"] = new string[] { @"Liberation Serif", @"Times New Roman", @"Times" };
            d[@"Comic Sans MS"] = new string[] { @"Liberation Sans", @"Arial" };
            d[@"Consolas"] = new string[] { @"Cascadia Mono", @"Cascadia Code", @"Liberation Mono", @"Courier New" };
            d[@"Constantia"] = new string[] { @"Caladea", @"Liberation Serif", @"Georgia", @"Times New Roman" };
            d[@"Corbel"] = new string[] { @"Carlito", @"Liberation Sans", @"Arial" };
            d[@"Courier"] = new string[] { @"Courier New", @"Liberation Mono" };
            d[@"Courier New"] = new string[] { @"Liberation Mono", @"Courier" };
            d[@"Garamond"] = new string[] { @"Liberation Serif", @"Times New Roman", @"Times" };
            d[@"Georgia"] = new string[] { @"Liberation Serif", @"Times New Roman", @"Times" };
            d[@"Helvetica"] = new string[] { @"Arial", @"Liberation Sans" };
            d[@"Helvetica Neue"] = new string[] { @"Helvetica", @"Arial", @"Liberation Sans" };
            d[@"Impact"] = new string[] { @"Liberation Sans Narrow", @"Arial Narrow", @"Arial Black", @"Arial" };
            d[@"Lucida Console"] = new string[] { @"DejaVu Sans Mono", @"Liberation Mono", @"Consolas", @"Courier New" };
            d[@"Lucida Sans Unicode"] = new string[] { @"DejaVu Sans", @"Liberation Sans", @"Arial" };
            d[@"MS Sans Serif"] = new string[] { @"Arial", @"Liberation Sans", @"Helvetica" };
            d[@"MS Serif"] = new string[] { @"Times New Roman", @"Liberation Serif", @"Times" };
            d[@"Palatino"] = new string[] { @"Palatino Linotype", @"Book Antiqua", @"Liberation Serif", @"Times New Roman" };
            d[@"Palatino Linotype"] = new string[] { @"Palatino", @"Book Antiqua", @"Liberation Serif", @"Times New Roman" };
            d[@"Segoe Print"] = new string[] { @"Comic Sans MS", @"Liberation Sans", @"Arial" };
            d[@"Segoe Script"] = new string[] { @"Comic Sans MS", @"Liberation Sans", @"Arial" };
            d[@"Segoe UI"] = new string[] { @"Liberation Sans", @"Arial", @"Helvetica" };
            d[@"Tahoma"] = new string[] { @"DejaVu Sans Condensed", @"DejaVu Sans", @"Liberation Sans", @"Arial" };
            d[@"Times"] = new string[] { @"Times New Roman", @"Liberation Serif" };
            d[@"Times New Roman"] = new string[] { @"Liberation Serif", @"Times" };
            d[@"Trebuchet MS"] = new string[] { @"Liberation Sans", @"Arial", @"Helvetica" };
            d[@"Verdana"] = new string[] { @"DejaVu Sans", @"Liberation Sans", @"Arial" };

            return d;
        }
    }
}
