<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFrameworks>net8.0;net9.0;netstandard2.1;netstandard2.0;net462</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
	<SignAssembly>true</SignAssembly>
	<AssemblyOriginatorKeyFile>EPPlus.Export.Pdf.snk</AssemblyOriginatorKeyFile>
	<LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="PDF\**" />
    <EmbeddedResource Remove="PDF\**" />
    <None Remove="PDF\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\EPPlus\src\EPPlus\EPPlus.csproj" />
    <ProjectReference Include="..\EPPlus.Fonts.OpenType\EPPlus.Fonts.OpenType.csproj" />
	  <ProjectReference Include="..\EPPlus.Graphics\EPPlus.Graphics.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Compile Remove="Core\Worksheet\Fonts\Tables\**" />
		<Compile Remove="FormulaParsing\Excel\Functions\DynamicArray\**" />
		<Compile Remove="FormulaParsing\FormulaExpressions\Variables\**" />
		<Compile Remove="Settings\**" />
		<Compile Remove="Utils\RecyclableMemoryStream\**" />
		<EmbeddedResource Remove="Core\Worksheet\Fonts\Tables\**" />
		<EmbeddedResource Remove="FormulaParsing\Excel\Functions\DynamicArray\**" />
		<EmbeddedResource Remove="FormulaParsing\FormulaExpressions\Variables\**" />
		<EmbeddedResource Remove="Settings\**" />
		<EmbeddedResource Remove="Utils\RecyclableMemoryStream\**" />
		<None Remove="Core\Worksheet\Fonts\Tables\**" />
		<None Remove="FormulaParsing\Excel\Functions\DynamicArray\**" />
		<None Remove="FormulaParsing\FormulaExpressions\Variables\**" />
		<None Remove="Settings\**" />
		<None Remove="Utils\RecyclableMemoryStream\**" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'net35'">
		<Reference Include="PresentationCore" />
		<Reference Include="PresentationFramework" />
		<Reference Include="System" />
		<Reference Include="System.configuration" />
		<Reference Include="System.Core" />
		<Reference Include="System.Data" />
		<Reference Include="System.Security" />
		<Reference Include="System.Xml" />
		<Reference Include="WindowsBase" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'net462'">
		<Reference Include="PresentationCore" />
		<Reference Include="System" />
		<Reference Include="System.configuration" />
		<Reference Include="System.Core" />
		<Reference Include="System.Data" />
		<Reference Include="System.Security" />
		<Reference Include="System.Xml" />
		<Reference Include="System.Threading.Tasks" />
		<PackageReference Include="System.ComponentModel.Annotations" />
		<PackageReference Include="Microsoft.IO.RecyclableMemoryStream" />
		<PackageReference Include="System.Security.Cryptography.Xml" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' != 'net35' and '$(TargetFramework)' != 'net462' and '$(TargetFramework)' != 'net9.0'">
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="Microsoft.IO.RecyclableMemoryStream" />
		<PackageReference Include="System.Security.Cryptography.Pkcs" />
		<PackageReference Include="System.ComponentModel.Annotations" />
		<PackageReference Include="System.Text.Encoding.CodePages" />
		<PackageReference Include="System.Security.Cryptography.Xml" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<PackageReference Include="Microsoft.IO.RecyclableMemoryStream" />
		<PackageReference Include="System.ComponentModel.Annotations" />
	</ItemGroup>

</Project>
