<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net9.0;net8.0;netstandard2.1;netstandard2.0;net462;net35</TargetFrameworks>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<Version>1.0.0</Version>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageLicenseFile>license.md</PackageLicenseFile>
		<RepositoryType>git</RepositoryType>
		<!--<SignAssembly>true</SignAssembly>
		<AssemblyOriginatorKeyFile>EPPlus.Interfaces.snk</AssemblyOriginatorKeyFile>-->
		<RootNamespace>EPPlus.Fonts.OpenType</RootNamespace>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
		<PackageIcon>EPPlusLogo.png</PackageIcon>
		<LangVersion>latest</LangVersion>
		<SignAssembly>True</SignAssembly>
		<AssemblyOriginatorKeyFile>EPPlus.Fonts.OpenType.snk</AssemblyOriginatorKeyFile>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0|AnyCPU'">
	  <Deterministic>False</Deterministic>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0|AnyCPU'">
	  <Deterministic>False</Deterministic>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard2.1|AnyCPU'">
	  <Deterministic>False</Deterministic>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard2.0|AnyCPU'">
	  <Deterministic>False</Deterministic>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net462|AnyCPU'">
	  <Deterministic>False</Deterministic>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net35|AnyCPU'">
	  <Deterministic>False</Deterministic>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0|AnyCPU'">
	  <Deterministic>False</Deterministic>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0|AnyCPU'">
	  <Deterministic>False</Deterministic>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard2.1|AnyCPU'">
	  <Deterministic>False</Deterministic>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard2.0|AnyCPU'">
	  <Deterministic>False</Deterministic>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net462|AnyCPU'">
	  <Deterministic>False</Deterministic>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net35|AnyCPU'">
	  <Deterministic>False</Deterministic>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="Tables\Cmap\Builders\**" />
	  <EmbeddedResource Remove="Tables\Cmap\Builders\**" />
	  <None Remove="Tables\Cmap\Builders\**" />
	</ItemGroup>
	<ItemGroup>
	  <Compile Remove="TtfFont.cs" />
	</ItemGroup>
	<ItemGroup>
		<None Include="EPPlusLogo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="license.md">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Include="readme.md">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\..\EPPlus\src\EPPlus.Interfaces\EPPlus.Interfaces.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="TextShaping\Positioning\" />
	</ItemGroup>
</Project>
