<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0;netstandard2.1;netstandard2.0;net462</TargetFrameworks>
    <AssemblyVersion>8.6.2.0</AssemblyVersion>
    <FileVersion>8.6.2.0</FileVersion>
    <Version>8.6.2</Version>
    <SignAssembly>true</SignAssembly>
    <PackageLicenseFile>license.md</PackageLicenseFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <AssemblyOriginatorKeyFile>EPPlus.System.Drawing.snk</AssemblyOriginatorKeyFile>
    <RootNamespace>OfficeOpenXml.System.Drawing</RootNamespace>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageIcon>EPPlusLogo.png</PackageIcon>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EPPlus.Interfaces\EPPlus.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' != 'net35' and '$(TargetFramework)' != 'net462' and '$(TargetFramework)' != 'net9.0' and '$(TargetFramework)' != 'net10.0'">
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
	<PackageReference Include="System.Drawing.Common" VersionOverride="9.0.11" />
  </ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<PackageReference Include="System.Drawing.Common" VersionOverride="10.0.1" />
	</ItemGroup>
	<ItemGroup>
    <None Include="EPPlusLogo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="license.md">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="readme.md">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>
</Project>