<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>net481;net8.0</TargetFrameworks>
	  <!-- Build servers only build and test .NET 8. Pass -p:TestAllFrameworks=true to include all frameworks. -->
	  <TargetFrameworks Condition="'$(CI)' == 'true' And '$(TestAllFrameworks)' != 'true'">net8.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>EPPlus.DrawingRenderer.Tests.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\EPPlus\src\EPPlus\EPPlus.csproj" />
    <ProjectReference Include="..\EPPlus.DrawingRenderer\EPPlus.DrawingRenderer.csproj" />
    <ProjectReference Include="..\EPPlus.Fonts.OpenType\EPPlus.Fonts.OpenType.csproj" />
    <ProjectReference Include="..\EPPlus.Graphics\EPPlus.Graphics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>


    <ItemGroup>
	    <PackageReference Include="Microsoft.NET.Test.Sdk" />
	    <PackageReference Include="MSTest.TestAdapter" />
	    <PackageReference Include="MSTest.TestFramework" />
    </ItemGroup>

</Project>
