### YamlMime:ManagedReference
items:
- uid: OfficeOpenXml.ExcelPackageSettings
  commentId: T:OfficeOpenXml.ExcelPackageSettings
  id: ExcelPackageSettings
  parent: OfficeOpenXml
  children:
  - OfficeOpenXml.ExcelPackageSettings.ApplyFiltersOnSave
  - OfficeOpenXml.ExcelPackageSettings.DoGarbageCollectOnDispose
  - OfficeOpenXml.ExcelPackageSettings.ImageSettings
  - OfficeOpenXml.ExcelPackageSettings.TextSettings
  langs:
  - csharp
  - vb
  name: ExcelPackageSettings
  nameWithType: ExcelPackageSettings
  fullName: OfficeOpenXml.ExcelPackageSettings
  type: Class
  source:
    remote:
      path: src/EPPlus/ExcelPackageSettings.cs
      branch: develop7
      repo: https://github.com/EPPlusSoftware/EPPlus.git
    id: ExcelPackageSettings
    path: ../src/EPPlus/ExcelPackageSettings.cs
    startLine: 19
  assemblies:
  - EPPlus
  namespace: OfficeOpenXml
  summary: "\nPackage generic settings\n"
  example: []
  syntax:
    content: public class ExcelPackageSettings
    content.vb: Public Class ExcelPackageSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: OfficeOpenXml.ExcelPackageSettings.DoGarbageCollectOnDispose
  commentId: P:OfficeOpenXml.ExcelPackageSettings.DoGarbageCollectOnDispose
  id: DoGarbageCollectOnDispose
  parent: OfficeOpenXml.ExcelPackageSettings
  langs:
  - csharp
  - vb
  name: DoGarbageCollectOnDispose
  nameWithType: ExcelPackageSettings.DoGarbageCollectOnDispose
  fullName: OfficeOpenXml.ExcelPackageSettings.DoGarbageCollectOnDispose
  type: Property
  source:
    remote:
      path: src/EPPlus/ExcelPackageSettings.cs
      branch: develop7
      repo: https://github.com/EPPlusSoftware/EPPlus.git
    id: DoGarbageCollectOnDispose
    path: ../src/EPPlus/ExcelPackageSettings.cs
    startLine: 28
  assemblies:
  - EPPlus
  namespace: OfficeOpenXml
  summary: "\nDo not call garbage collection when ExcelPackage is disposed.\n"
  example: []
  syntax:
    content: public bool DoGarbageCollectOnDispose { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property DoGarbageCollectOnDispose As Boolean
  overload: OfficeOpenXml.ExcelPackageSettings.DoGarbageCollectOnDispose*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: OfficeOpenXml.ExcelPackageSettings.TextSettings
  commentId: P:OfficeOpenXml.ExcelPackageSettings.TextSettings
  id: TextSettings
  parent: OfficeOpenXml.ExcelPackageSettings
  langs:
  - csharp
  - vb
  name: TextSettings
  nameWithType: ExcelPackageSettings.TextSettings
  fullName: OfficeOpenXml.ExcelPackageSettings.TextSettings
  type: Property
  source:
    remote:
      path: src/EPPlus/ExcelPackageSettings.cs
      branch: develop7
      repo: https://github.com/EPPlusSoftware/EPPlus.git
    id: TextSettings
    path: ../src/EPPlus/ExcelPackageSettings.cs
    startLine: 34
  assemblies:
  - EPPlus
  namespace: OfficeOpenXml
  summary: "\nManage text settings such as measurement of text for the Autofit functions.\n"
  example: []
  syntax:
    content: public ExcelTextSettings TextSettings { get; }
    parameters: []
    return:
      type: OfficeOpenXml.ExcelTextSettings
    content.vb: Public ReadOnly Property TextSettings As ExcelTextSettings
  overload: OfficeOpenXml.ExcelPackageSettings.TextSettings*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: OfficeOpenXml.ExcelPackageSettings.ImageSettings
  commentId: P:OfficeOpenXml.ExcelPackageSettings.ImageSettings
  id: ImageSettings
  parent: OfficeOpenXml.ExcelPackageSettings
  langs:
  - csharp
  - vb
  name: ImageSettings
  nameWithType: ExcelPackageSettings.ImageSettings
  fullName: OfficeOpenXml.ExcelPackageSettings.ImageSettings
  type: Property
  source:
    remote:
      path: src/EPPlus/ExcelPackageSettings.cs
      branch: develop7
      repo: https://github.com/EPPlusSoftware/EPPlus.git
    id: ImageSettings
    path: ../src/EPPlus/ExcelPackageSettings.cs
    startLine: 49
  assemblies:
  - EPPlus
  namespace: OfficeOpenXml
  summary: "\nSet the handler for getting image bounds. \n"
  example: []
  syntax:
    content: public ExcelImageSettings ImageSettings { get; }
    parameters: []
    return:
      type: OfficeOpenXml.ExcelImageSettings
    content.vb: Public ReadOnly Property ImageSettings As ExcelImageSettings
  overload: OfficeOpenXml.ExcelPackageSettings.ImageSettings*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: OfficeOpenXml.ExcelPackageSettings.ApplyFiltersOnSave
  commentId: P:OfficeOpenXml.ExcelPackageSettings.ApplyFiltersOnSave
  id: ApplyFiltersOnSave
  parent: OfficeOpenXml.ExcelPackageSettings
  langs:
  - csharp
  - vb
  name: ApplyFiltersOnSave
  nameWithType: ExcelPackageSettings.ApplyFiltersOnSave
  fullName: OfficeOpenXml.ExcelPackageSettings.ApplyFiltersOnSave
  type: Property
  source:
    remote:
      path: src/EPPlus/ExcelPackageSettings.cs
      branch: develop7
      repo: https://github.com/EPPlusSoftware/EPPlus.git
    id: ApplyFiltersOnSave
    path: ../src/EPPlus/ExcelPackageSettings.cs
    startLine: 65
  assemblies:
  - EPPlus
  namespace: OfficeOpenXml
  summary: "\nAny auto- or table- filters created will be applied on save.\nIn the case you want to handle this manually, set this property to true.\n"
  example: []
  syntax:
    content: public bool ApplyFiltersOnSave { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property ApplyFiltersOnSave As Boolean
  overload: OfficeOpenXml.ExcelPackageSettings.ApplyFiltersOnSave*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: OfficeOpenXml
  commentId: N:OfficeOpenXml
  name: OfficeOpenXml
  nameWithType: OfficeOpenXml
  fullName: OfficeOpenXml
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: OfficeOpenXml.ExcelPackageSettings.DoGarbageCollectOnDispose*
  commentId: Overload:OfficeOpenXml.ExcelPackageSettings.DoGarbageCollectOnDispose
  name: DoGarbageCollectOnDispose
  nameWithType: ExcelPackageSettings.DoGarbageCollectOnDispose
  fullName: OfficeOpenXml.ExcelPackageSettings.DoGarbageCollectOnDispose
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: OfficeOpenXml.ExcelPackageSettings.TextSettings*
  commentId: Overload:OfficeOpenXml.ExcelPackageSettings.TextSettings
  name: TextSettings
  nameWithType: ExcelPackageSettings.TextSettings
  fullName: OfficeOpenXml.ExcelPackageSettings.TextSettings
- uid: OfficeOpenXml.ExcelTextSettings
  commentId: T:OfficeOpenXml.ExcelTextSettings
  parent: OfficeOpenXml
  name: ExcelTextSettings
  nameWithType: ExcelTextSettings
  fullName: OfficeOpenXml.ExcelTextSettings
- uid: OfficeOpenXml.ExcelPackageSettings.ImageSettings*
  commentId: Overload:OfficeOpenXml.ExcelPackageSettings.ImageSettings
  name: ImageSettings
  nameWithType: ExcelPackageSettings.ImageSettings
  fullName: OfficeOpenXml.ExcelPackageSettings.ImageSettings
- uid: OfficeOpenXml.ExcelImageSettings
  commentId: T:OfficeOpenXml.ExcelImageSettings
  parent: OfficeOpenXml
  name: ExcelImageSettings
  nameWithType: ExcelImageSettings
  fullName: OfficeOpenXml.ExcelImageSettings
- uid: OfficeOpenXml.ExcelPackageSettings.ApplyFiltersOnSave*
  commentId: Overload:OfficeOpenXml.ExcelPackageSettings.ApplyFiltersOnSave
  name: ApplyFiltersOnSave
  nameWithType: ExcelPackageSettings.ApplyFiltersOnSave
  fullName: OfficeOpenXml.ExcelPackageSettings.ApplyFiltersOnSave
