### YamlMime:ManagedReference
items:
- uid: OfficeOpenXml.ExcelTextSettings
  commentId: T:OfficeOpenXml.ExcelTextSettings
  id: ExcelTextSettings
  parent: OfficeOpenXml
  children:
  - OfficeOpenXml.ExcelTextSettings.AutofitScaleFactor
  - OfficeOpenXml.ExcelTextSettings.FallbackTextMeasurer
  - OfficeOpenXml.ExcelTextSettings.GenericTextMeasurer
  - OfficeOpenXml.ExcelTextSettings.PrimaryTextMeasurer
  langs:
  - csharp
  - vb
  name: ExcelTextSettings
  nameWithType: ExcelTextSettings
  fullName: OfficeOpenXml.ExcelTextSettings
  type: Class
  source:
    remote:
      path: src/EPPlus/ExcelTextSettings.cs
      branch: fix/comments-and-warings
      repo: https://github.com/EPPlusSoftware/EPPlus.git
    id: ExcelTextSettings
    path: ../src/EPPlus/ExcelTextSettings.cs
    startLine: 23
  assemblies:
  - EPPlus
  namespace: OfficeOpenXml
  summary: "\nThis class contains settings for text measurement.\n"
  example: []
  syntax:
    content: public class ExcelTextSettings
    content.vb: Public Class ExcelTextSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: OfficeOpenXml.ExcelTextSettings.PrimaryTextMeasurer
  commentId: P:OfficeOpenXml.ExcelTextSettings.PrimaryTextMeasurer
  id: PrimaryTextMeasurer
  parent: OfficeOpenXml.ExcelTextSettings
  langs:
  - csharp
  - vb
  name: PrimaryTextMeasurer
  nameWithType: ExcelTextSettings.PrimaryTextMeasurer
  fullName: OfficeOpenXml.ExcelTextSettings.PrimaryTextMeasurer
  type: Property
  source:
    remote:
      path: src/EPPlus/ExcelTextSettings.cs
      branch: fix/comments-and-warings
      repo: https://github.com/EPPlusSoftware/EPPlus.git
    id: PrimaryTextMeasurer
    path: ../src/EPPlus/ExcelTextSettings.cs
    startLine: 66
  assemblies:
  - EPPlus
  namespace: OfficeOpenXml
  summary: "\nThis is the primary text measurer\n"
  example: []
  syntax:
    content: public ITextMeasurer PrimaryTextMeasurer { get; set; }
    parameters: []
    return:
      type: OfficeOpenXml.Interfaces.Drawing.Text.ITextMeasurer
    content.vb: Public Property PrimaryTextMeasurer As ITextMeasurer
  overload: OfficeOpenXml.ExcelTextSettings.PrimaryTextMeasurer*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: OfficeOpenXml.ExcelTextSettings.FallbackTextMeasurer
  commentId: P:OfficeOpenXml.ExcelTextSettings.FallbackTextMeasurer
  id: FallbackTextMeasurer
  parent: OfficeOpenXml.ExcelTextSettings
  langs:
  - csharp
  - vb
  name: FallbackTextMeasurer
  nameWithType: ExcelTextSettings.FallbackTextMeasurer
  fullName: OfficeOpenXml.ExcelTextSettings.FallbackTextMeasurer
  type: Property
  source:
    remote:
      path: src/EPPlus/ExcelTextSettings.cs
      branch: fix/comments-and-warings
      repo: https://github.com/EPPlusSoftware/EPPlus.git
    id: FallbackTextMeasurer
    path: ../src/EPPlus/ExcelTextSettings.cs
    startLine: 71
  assemblies:
  - EPPlus
  namespace: OfficeOpenXml
  summary: "\nIf the primary text measurer fails to measure the text, this one will be used.\n"
  example: []
  syntax:
    content: public ITextMeasurer FallbackTextMeasurer { get; set; }
    parameters: []
    return:
      type: OfficeOpenXml.Interfaces.Drawing.Text.ITextMeasurer
    content.vb: Public Property FallbackTextMeasurer As ITextMeasurer
  overload: OfficeOpenXml.ExcelTextSettings.FallbackTextMeasurer*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: OfficeOpenXml.ExcelTextSettings.AutofitScaleFactor
  commentId: P:OfficeOpenXml.ExcelTextSettings.AutofitScaleFactor
  id: AutofitScaleFactor
  parent: OfficeOpenXml.ExcelTextSettings
  langs:
  - csharp
  - vb
  name: AutofitScaleFactor
  nameWithType: ExcelTextSettings.AutofitScaleFactor
  fullName: OfficeOpenXml.ExcelTextSettings.AutofitScaleFactor
  type: Property
  source:
    remote:
      path: src/EPPlus/ExcelTextSettings.cs
      branch: fix/comments-and-warings
      repo: https://github.com/EPPlusSoftware/EPPlus.git
    id: AutofitScaleFactor
    path: ../src/EPPlus/ExcelTextSettings.cs
    startLine: 76
  assemblies:
  - EPPlus
  namespace: OfficeOpenXml
  summary: "\nAll measurements of texts will be multiplied with this value. Default is 1.\n"
  example: []
  syntax:
    content: public float AutofitScaleFactor { get; set; }
    parameters: []
    return:
      type: System.Single
    content.vb: Public Property AutofitScaleFactor As Single
  overload: OfficeOpenXml.ExcelTextSettings.AutofitScaleFactor*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: OfficeOpenXml.ExcelTextSettings.GenericTextMeasurer
  commentId: P:OfficeOpenXml.ExcelTextSettings.GenericTextMeasurer
  id: GenericTextMeasurer
  parent: OfficeOpenXml.ExcelTextSettings
  langs:
  - csharp
  - vb
  name: GenericTextMeasurer
  nameWithType: ExcelTextSettings.GenericTextMeasurer
  fullName: OfficeOpenXml.ExcelTextSettings.GenericTextMeasurer
  type: Property
  source:
    remote:
      path: src/EPPlus/ExcelTextSettings.cs
      branch: fix/comments-and-warings
      repo: https://github.com/EPPlusSoftware/EPPlus.git
    id: GenericTextMeasurer
    path: ../src/EPPlus/ExcelTextSettings.cs
    startLine: 80
  assemblies:
  - EPPlus
  namespace: OfficeOpenXml
  summary: "\nReturns an instance of the internal generic text measurer\n"
  example: []
  syntax:
    content: public ITextMeasurer GenericTextMeasurer { get; }
    parameters: []
    return:
      type: OfficeOpenXml.Interfaces.Drawing.Text.ITextMeasurer
    content.vb: Public ReadOnly Property GenericTextMeasurer As ITextMeasurer
  overload: OfficeOpenXml.ExcelTextSettings.GenericTextMeasurer*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: OfficeOpenXml
  commentId: N:OfficeOpenXml
  name: OfficeOpenXml
  nameWithType: OfficeOpenXml
  fullName: OfficeOpenXml
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: OfficeOpenXml.ExcelTextSettings.PrimaryTextMeasurer*
  commentId: Overload:OfficeOpenXml.ExcelTextSettings.PrimaryTextMeasurer
  name: PrimaryTextMeasurer
  nameWithType: ExcelTextSettings.PrimaryTextMeasurer
  fullName: OfficeOpenXml.ExcelTextSettings.PrimaryTextMeasurer
- uid: OfficeOpenXml.Interfaces.Drawing.Text.ITextMeasurer
  commentId: T:OfficeOpenXml.Interfaces.Drawing.Text.ITextMeasurer
  parent: OfficeOpenXml.Interfaces.Drawing.Text
  name: ITextMeasurer
  nameWithType: ITextMeasurer
  fullName: OfficeOpenXml.Interfaces.Drawing.Text.ITextMeasurer
- uid: OfficeOpenXml.Interfaces.Drawing.Text
  commentId: N:OfficeOpenXml.Interfaces.Drawing.Text
  name: OfficeOpenXml.Interfaces.Drawing.Text
  nameWithType: OfficeOpenXml.Interfaces.Drawing.Text
  fullName: OfficeOpenXml.Interfaces.Drawing.Text
- uid: OfficeOpenXml.ExcelTextSettings.FallbackTextMeasurer*
  commentId: Overload:OfficeOpenXml.ExcelTextSettings.FallbackTextMeasurer
  name: FallbackTextMeasurer
  nameWithType: ExcelTextSettings.FallbackTextMeasurer
  fullName: OfficeOpenXml.ExcelTextSettings.FallbackTextMeasurer
- uid: OfficeOpenXml.ExcelTextSettings.AutofitScaleFactor*
  commentId: Overload:OfficeOpenXml.ExcelTextSettings.AutofitScaleFactor
  name: AutofitScaleFactor
  nameWithType: ExcelTextSettings.AutofitScaleFactor
  fullName: OfficeOpenXml.ExcelTextSettings.AutofitScaleFactor
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  name: Single
  nameWithType: Single
  fullName: System.Single
- uid: OfficeOpenXml.ExcelTextSettings.GenericTextMeasurer*
  commentId: Overload:OfficeOpenXml.ExcelTextSettings.GenericTextMeasurer
  name: GenericTextMeasurer
  nameWithType: ExcelTextSettings.GenericTextMeasurer
  fullName: OfficeOpenXml.ExcelTextSettings.GenericTextMeasurer
