### YamlMime:ManagedReference
items:
- uid: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings
  commentId: T:OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings
  id: CssRangeExportSettings
  parent: OfficeOpenXml.Export.HtmlExport
  children:
  - OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.Copy(OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings)
  - OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.CssExclude
  - OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.ResetToDefault
  langs:
  - csharp
  - vb
  name: CssRangeExportSettings
  nameWithType: CssRangeExportSettings
  fullName: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings
  type: Class
  source:
    remote:
      path: src/EPPlus/Export/HtmlExport/Settings/CssRangeExportSettings.cs
      branch: develop7
      repo: https://github.com/EPPlusSoftware/EPPlus.git
    id: CssRangeExportSettings
    path: ../src/EPPlus/Export/HtmlExport/Settings/CssRangeExportSettings.cs
    startLine: 18
  assemblies:
  - EPPlus
  namespace: OfficeOpenXml.Export.HtmlExport
  summary: "\nSettings for css export for tables\n"
  example: []
  syntax:
    content: 'public class CssRangeExportSettings : CssExportSettings'
    content.vb: >-
      Public Class CssRangeExportSettings
          Inherits CssExportSettings
  inheritance:
  - System.Object
  - OfficeOpenXml.Export.HtmlExport.CssExportSettings
  inheritedMembers:
  - OfficeOpenXml.Export.HtmlExport.CssExportSettings.IncludeSharedClasses
  - OfficeOpenXml.Export.HtmlExport.CssExportSettings.IncludeNormalFont
  - OfficeOpenXml.Export.HtmlExport.CssExportSettings.IncludeCssReset
  - OfficeOpenXml.Export.HtmlExport.CssExportSettings.AdditionalCssElements
  - OfficeOpenXml.Export.HtmlExport.CssExportSettings.IndentValue
  - OfficeOpenXml.Export.HtmlExport.CssExportSettings.IndentUnit
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.CssExclude
  commentId: P:OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.CssExclude
  id: CssExclude
  parent: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings
  langs:
  - csharp
  - vb
  name: CssExclude
  nameWithType: CssRangeExportSettings.CssExclude
  fullName: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.CssExclude
  type: Property
  source:
    remote:
      path: src/EPPlus/Export/HtmlExport/Settings/CssRangeExportSettings.cs
      branch: develop7
      repo: https://github.com/EPPlusSoftware/EPPlus.git
    id: CssExclude
    path: ../src/EPPlus/Export/HtmlExport/Settings/CssRangeExportSettings.cs
    startLine: 27
  assemblies:
  - EPPlus
  namespace: OfficeOpenXml.Export.HtmlExport
  summary: "\nSettings to exclude specific styles from the css.\n"
  example: []
  syntax:
    content: public CssExclude CssExclude { get; }
    parameters: []
    return:
      type: OfficeOpenXml.Export.HtmlExport.CssExclude
    content.vb: Public ReadOnly Property CssExclude As CssExclude
  overload: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.CssExclude*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.ResetToDefault
  commentId: M:OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.ResetToDefault
  id: ResetToDefault
  parent: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings
  langs:
  - csharp
  - vb
  name: ResetToDefault()
  nameWithType: CssRangeExportSettings.ResetToDefault()
  fullName: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.ResetToDefault()
  type: Method
  source:
    remote:
      path: src/EPPlus/Export/HtmlExport/Settings/CssRangeExportSettings.cs
      branch: develop7
      repo: https://github.com/EPPlusSoftware/EPPlus.git
    id: ResetToDefault
    path: ../src/EPPlus/Export/HtmlExport/Settings/CssRangeExportSettings.cs
    startLine: 31
  assemblies:
  - EPPlus
  namespace: OfficeOpenXml.Export.HtmlExport
  summary: "\nReset the settings to it&apos;s default values.\n"
  example: []
  syntax:
    content: public void ResetToDefault()
    content.vb: Public Sub ResetToDefault
  overload: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.ResetToDefault*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.Copy(OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings)
  commentId: M:OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.Copy(OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings)
  id: Copy(OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings)
  parent: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings
  langs:
  - csharp
  - vb
  name: Copy(CssRangeExportSettings)
  nameWithType: CssRangeExportSettings.Copy(CssRangeExportSettings)
  fullName: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.Copy(OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings)
  type: Method
  source:
    remote:
      path: src/EPPlus/Export/HtmlExport/Settings/CssRangeExportSettings.cs
      branch: develop7
      repo: https://github.com/EPPlusSoftware/EPPlus.git
    id: Copy
    path: ../src/EPPlus/Export/HtmlExport/Settings/CssRangeExportSettings.cs
    startLine: 40
  assemblies:
  - EPPlus
  namespace: OfficeOpenXml.Export.HtmlExport
  summary: "\nCopy the values from another settings object.\n"
  example: []
  syntax:
    content: public void Copy(CssRangeExportSettings copy)
    parameters:
    - id: copy
      type: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings
      description: The object to copy.
    content.vb: Public Sub Copy(copy As CssRangeExportSettings)
  overload: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.Copy*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: OfficeOpenXml.Export.HtmlExport
  commentId: N:OfficeOpenXml.Export.HtmlExport
  name: OfficeOpenXml.Export.HtmlExport
  nameWithType: OfficeOpenXml.Export.HtmlExport
  fullName: OfficeOpenXml.Export.HtmlExport
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: OfficeOpenXml.Export.HtmlExport.CssExportSettings
  commentId: T:OfficeOpenXml.Export.HtmlExport.CssExportSettings
  parent: OfficeOpenXml.Export.HtmlExport
  name: CssExportSettings
  nameWithType: CssExportSettings
  fullName: OfficeOpenXml.Export.HtmlExport.CssExportSettings
- uid: OfficeOpenXml.Export.HtmlExport.CssExportSettings.IncludeSharedClasses
  commentId: P:OfficeOpenXml.Export.HtmlExport.CssExportSettings.IncludeSharedClasses
  parent: OfficeOpenXml.Export.HtmlExport.CssExportSettings
  name: IncludeSharedClasses
  nameWithType: CssExportSettings.IncludeSharedClasses
  fullName: OfficeOpenXml.Export.HtmlExport.CssExportSettings.IncludeSharedClasses
- uid: OfficeOpenXml.Export.HtmlExport.CssExportSettings.IncludeNormalFont
  commentId: P:OfficeOpenXml.Export.HtmlExport.CssExportSettings.IncludeNormalFont
  parent: OfficeOpenXml.Export.HtmlExport.CssExportSettings
  name: IncludeNormalFont
  nameWithType: CssExportSettings.IncludeNormalFont
  fullName: OfficeOpenXml.Export.HtmlExport.CssExportSettings.IncludeNormalFont
- uid: OfficeOpenXml.Export.HtmlExport.CssExportSettings.IncludeCssReset
  commentId: P:OfficeOpenXml.Export.HtmlExport.CssExportSettings.IncludeCssReset
  parent: OfficeOpenXml.Export.HtmlExport.CssExportSettings
  name: IncludeCssReset
  nameWithType: CssExportSettings.IncludeCssReset
  fullName: OfficeOpenXml.Export.HtmlExport.CssExportSettings.IncludeCssReset
- uid: OfficeOpenXml.Export.HtmlExport.CssExportSettings.AdditionalCssElements
  commentId: P:OfficeOpenXml.Export.HtmlExport.CssExportSettings.AdditionalCssElements
  parent: OfficeOpenXml.Export.HtmlExport.CssExportSettings
  name: AdditionalCssElements
  nameWithType: CssExportSettings.AdditionalCssElements
  fullName: OfficeOpenXml.Export.HtmlExport.CssExportSettings.AdditionalCssElements
- uid: OfficeOpenXml.Export.HtmlExport.CssExportSettings.IndentValue
  commentId: P:OfficeOpenXml.Export.HtmlExport.CssExportSettings.IndentValue
  parent: OfficeOpenXml.Export.HtmlExport.CssExportSettings
  name: IndentValue
  nameWithType: CssExportSettings.IndentValue
  fullName: OfficeOpenXml.Export.HtmlExport.CssExportSettings.IndentValue
- uid: OfficeOpenXml.Export.HtmlExport.CssExportSettings.IndentUnit
  commentId: P:OfficeOpenXml.Export.HtmlExport.CssExportSettings.IndentUnit
  parent: OfficeOpenXml.Export.HtmlExport.CssExportSettings
  name: IndentUnit
  nameWithType: CssExportSettings.IndentUnit
  fullName: OfficeOpenXml.Export.HtmlExport.CssExportSettings.IndentUnit
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.CssExclude*
  commentId: Overload:OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.CssExclude
  name: CssExclude
  nameWithType: CssRangeExportSettings.CssExclude
  fullName: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.CssExclude
- uid: OfficeOpenXml.Export.HtmlExport.CssExclude
  commentId: T:OfficeOpenXml.Export.HtmlExport.CssExclude
  parent: OfficeOpenXml.Export.HtmlExport
  name: CssExclude
  nameWithType: CssExclude
  fullName: OfficeOpenXml.Export.HtmlExport.CssExclude
- uid: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.ResetToDefault*
  commentId: Overload:OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.ResetToDefault
  name: ResetToDefault
  nameWithType: CssRangeExportSettings.ResetToDefault
  fullName: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.ResetToDefault
- uid: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.Copy*
  commentId: Overload:OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.Copy
  name: Copy
  nameWithType: CssRangeExportSettings.Copy
  fullName: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings.Copy
- uid: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings
  commentId: T:OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings
  parent: OfficeOpenXml.Export.HtmlExport
  name: CssRangeExportSettings
  nameWithType: CssRangeExportSettings
  fullName: OfficeOpenXml.Export.HtmlExport.CssRangeExportSettings
