name: AI Code Review
on:
    pull_request:
      types: [opened, synchronize, reopened, closed]
    issue_comment:
      types: [created]
    pull_request_review_comment:
      types: [created]
jobs:
    review:
      if: github.actor != 'perotoolsbot[bot]'
      uses: peroperogames/ToolsWorkflow/.github/workflows/code-review.yml@main
      secrets: inherit
