name: Build Release Branches SBOM Test

on:
  workflow_dispatch:

jobs:
  sbom:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/EPPlus.sln

    - name: Install CycloneDX
      run: dotnet tool install --global CycloneDX

    - name: Read version from csproj
      id: read_version
      run: |
        $version = ([xml](Get-Content ./src/EPPlus/EPPlus.csproj)).Project.PropertyGroup.Version | Where-Object { $_ } | Select-Object -First 1
        echo "VERSION=$version" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Generate SBOM
      run: dotnet CycloneDX ./src/EPPlus/EPPlus.csproj -o ./sbom -F Json -st Library -sv ${{ env.VERSION }} -fn epplus-${{ env.VERSION }}.sbom.json -imp ./src/EPPlus/sbom-metadata-template.xml

    - name: Upload SBOM as artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: ./sbom/epplus-${{ env.VERSION }}.sbom.json

    - name: Authenticate to Azure
      uses: Azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.EPPLUS_CODE_SIGNING_APPLICATION_ID }}","clientSecret":"${{ secrets.EPPLUS_CODE_SIGNING_SECRET }}","subscriptionId":"${{ secrets.EPPLUS_CODE_SIGNING_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.EPPLUS_CODE_SIGNING_TENENT_ID }}"}'

    - name: Upload SBOM to Azure Blob Storage
      run: |
        az storage blob upload `
          --account-name eppluswebprod `
          --container-name sbom `
          --name epplus-${{ env.VERSION }}.sbom.json `
          --file ./sbom/epplus-${{ env.VERSION }}.sbom.json `
          --auth-mode login `
          --overwrite
      shell: pwsh
